<?php

namespace app\modules\miscellaneouse\API\ClashRoyale;

use yii;
use yii\web\View;
use yii\helpers\Url;

use app\modules\miscellaneouse\API\ClashRoyale\models\CardDatabase;

use app\modules\miscellaneouse\models\formModels\ProfilePicForm;

/**
 * Class RoyaleAPICalls
 * @package app\modules\core\miscellaneouse\API\ClashRoyale
 * @property int $apiToken
 */
 class RoyaleAPICalls
{
    private $apiToken = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjEzMmZmZmY3LTExNGItNGRiYy1iNjhkLWMzNDY2ZDAyNjc3MCIsImlhdCI6MTYwMDc1OTkxMCwic3ViIjoiZGV2ZWxvcGVyL2RiNjU5M2Q1LTVjMzAtZTZlNS1jMDNhLWI4ZjdiNjQ1ZDg3MSIsInNjb3BlcyI6WyJyb3lhbGUiXSwibGltaXRzIjpbeyJ0aWVyIjoiZGV2ZWxvcGVyL3NpbHZlciIsInR5cGUiOiJ0aHJvdHRsaW5nIn0seyJjaWRycyI6WyI4Ny4xNDAuMzIuMjEiLCI5NS4yMTYuMjM5LjE2MyJdLCJ0eXBlIjoiY2xpZW50In1dfQ.R7AgASQFFy_m_FGEjF1g3VnXPfxFY-anU5y2XYPoS2gxoqeS_R2V1rfTRgTZNH6qpYzH11zfp4VUrrS0go3bWw';

    /**
     * RoyaleAPICalls constructor.
     */
    public function __construct() { }

    public function getPlayerData($user)
    {
        $Player = $user->getPlayerId(3);
        $Player['player_id'] = str_replace("#", "%23", $Player['player_id']);

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api.clashroyale.com/v1/players/' . $Player['player_id']);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


        $headers = array();
        $headers[] = 'Accept: application/json';
        $headers[] = 'Authorization: Bearer ' . $this->apiToken;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return json_decode($result, true);
	}

    public function getBracketData($user)
    {
        $Player = $user->getPlayerId(3);
        $Player['player_id'] = str_replace("#", "%23", $Player['player_id']);

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api.clashroyale.com/v1/players/' . $Player['player_id'] . '/battlelog');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


        $headers = array();
        $headers[] = 'Accept: application/json';
        $headers[] = 'Authorization: Bearer ' . $this->apiToken;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        return json_decode($result, true);
	}

    public function updateCardDatabase()
    {
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, 'https://api.clashroyale.com/v1/cards');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


        $headers = array();
        $headers[] = 'Accept: application/json';
        $headers[] = 'Authorization: Bearer ' . $this->apiToken;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

        $cardDataArray = json_decode($result, true);

        foreach ($cardDataArray['items'] as $key => $cardData)
        {
            $model = CardDatabase::find()->where(['card_id' => $cardData['id']])->one();

            if(!$model)
                $model  = new CardDatabase();

            $model->card_id = $cardData['id'];
            $model->name = $cardData['name'];
            $model->max_level = $cardData['maxLevel'];

            $this->saveImage($cardData['iconUrls']['medium'],$cardData['id'] );
            
            $model->icon = $cardData['id'];

            $model->save();
		}
	}

    private function saveImage($imgUrl, $imgId)
    {
        $docRoot = Yii::getAlias("@app") . '/web/images/clashRoyale/cards/';

        $loadedImg = file_get_contents($imgUrl);

        $filePathPng = $docRoot . $imgId . '.png';
        $filePathWebp = $docRoot . $imgId . '.webp';

        if (!is_dir($docRoot)) {
            mkdir($docRoot, 0777, true);
        }

        file_put_contents($filePathPng, $loadedImg);

        $im = imagecreatefrompng($filePathPng);
        imagewebp($im, $filePathWebp);
	}
}